  name: 'Pipleline for Frontend'
  on:
    workflow_dispatch:
    push:
      branches:
        - master
  jobs:
    build:
      environment: dev
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        # setup nodejs environment
        - name: Setup Node.js environment
          uses: actions/setup-node@v4
          with:
            node-version: 18
            cache: 'npm'
            cache-dependency-path: "**/package.json"
        - name: Install dependencies
          run: yarn

        - name: Compile
          run: |
            make build docker=1 arch=amd64
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Push the image to Docker Hub
          run: |
            make push
